export const SymptomsOptions = [
  { label: "Abdominal Pain", value: "Abdominal Pain" },
  { label: "Back Pain", value: "Back Pain" },
  { label: "Chest Pain", value: "Chest Pain" },
  { label: "Shortness of Breath", value: "Shortness of Breath" },
  { label: "Cough", value: "Cough" },
  { label: "Fever", value: "Fever" },
  { label: "Chills", value: "Chills" },
  { label: "Nausea", value: "Nausea" },
  { label: "Vomiting", value: "Vomiting" },
  { label: "Diarrhea", value: "Diarrhea" },
  { label: "Constipation", value: "Constipation" },
  { label: "Headache", value: "Headache" },
  { label: "Dizziness", value: "Dizziness" },
  { label: "Fatigue", value: "Fatigue" },
  { label: "Muscle Pain", value: "Muscle Pain" },
  { label: "Joint Pain", value: "Joint Pain" },
  { label: "Rash", value: "Rash" },
  { label: "Itching", value: "Itching" },
  { label: "Swelling", value: "Swelling" },
  { label: "Bruising", value: "Bruising" },
  { label: "Weight Loss", value: "Weight Loss" },
  { label: "Weight Gain", value: "Weight Gain" },
  { label: "Loss of Appetite", value: "Loss of Appetite" },
  { label: "Night Sweats", value: "Night Sweats" },
  { label: "Palpitations", value: "Palpitations" },
  { label: "Anxiety", value: "Anxiety" },
  { label: "Depression", value: "Depression" },
  { label: "Insomnia", value: "Insomnia" },
  { label: "Blurred Vision", value: "Blurred Vision" },
  { label: "Hearing Loss", value: "Hearing Loss" },
  { label: "Sneezing", value: "Sneezing" },
  { label: "Runny Nose", value: "Runny Nose" },
  { label: "Sore Throat", value: "Sore Throat" },
  { label: "Swollen Lymph Nodes", value: "Swollen Lymph Nodes" },
  { label: "Bruising Easily", value: "Bruising Easily" },
  { label: "Memory Loss", value: "Memory Loss" },
  { label: "Confusion", value: "Confusion" },
  { label: "Seizures", value: "Seizures" },
  { label: "Tremors", value: "Tremors" },
  { label: "Numbness", value: "Numbness" },
  { label: "Tingling", value: "Tingling" },
  { label: "Frequent Urination", value: "Frequent Urination" },
  { label: "Painful Urination", value: "Painful Urination" },
  { label: "Blood in Urine", value: "Blood in Urine" },
  { label: "Frequent Thirst", value: "Frequent Thirst" },
  { label: "Hair Loss", value: "Hair Loss" },
  { label: "Dry Skin", value: "Dry Skin" },
  { label: "Easy Bruising", value: "Easy Bruising" },
  { label: "Fainting", value: "Fainting" },
];

export const LabTestsOptions = [
  { label: "Complete Blood Count (CBC)", value: "CBC" },
  { label: "Basic Metabolic Panel (BMP)", value: "BMP" },
  { label: "Comprehensive Metabolic Panel (CMP)", value: "CMP" },
  { label: "Lipid Panel", value: "Lipid Panel" },
  { label: "Liver Function Tests (LFTs)", value: "LFTs" },
  { label: "Kidney Function Tests", value: "Kidney Function Tests" },
  { label: "Thyroid Stimulating Hormone (TSH)", value: "TSH" },
  { label: "Free T4", value: "Free T4" },
  { label: "Free T3", value: "Free T3" },
  { label: "Hemoglobin A1c (HbA1c)", value: "HbA1c" },
  { label: "Urinalysis", value: "Urinalysis" },
  { label: "Urine Culture", value: "Urine Culture" },
  { label: "Blood Culture", value: "Blood Culture" },
  { label: "Prothrombin Time (PT)", value: "PT" },
  { label: "Partial Thromboplastin Time (PTT)", value: "PTT" },
  { label: "International Normalized Ratio (INR)", value: "INR" },
  { label: "C-Reactive Protein (CRP)", value: "CRP" },
  { label: "Erythrocyte Sedimentation Rate (ESR)", value: "ESR" },
  { label: "Vitamin D", value: "Vitamin D" },
  { label: "Vitamin B12", value: "Vitamin B12" },
  { label: "Folate", value: "Folate" },
  { label: "Iron Studies", value: "Iron Studies" },
  { label: "Ferritin", value: "Ferritin" },
  { label: "Transferrin", value: "Transferrin" },
  { label: "Electrolytes", value: "Electrolytes" },
  { label: "Calcium", value: "Calcium" },
  { label: "Magnesium", value: "Magnesium" },
  { label: "Phosphate", value: "Phosphate" },
  { label: "Creatine Kinase (CK)", value: "CK" },
  { label: "Troponin I/T", value: "Troponin" },
  { label: "Brain Natriuretic Peptide (BNP)", value: "BNP" },
  { label: "Urine Microalbumin", value: "Urine Microalbumin" },
  { label: "Pregnancy Test (hCG)", value: "Pregnancy Test" },
  { label: "Stool Occult Blood Test", value: "Stool Occult Blood Test" },
  { label: "HIV Test", value: "HIV Test" },
  {
    label: "Hepatitis B Surface Antigen",
    value: "Hepatitis B Surface Antigen",
  },
  { label: "Hepatitis C Antibody", value: "Hepatitis C Antibody" },
  { label: "Blood Glucose", value: "Blood Glucose" },
  { label: "Fasting Glucose", value: "Fasting Glucose" },
  { label: "Oral Glucose Tolerance Test (OGTT)", value: "OGTT" },
  { label: "Glycated Hemoglobin", value: "Glycated Hemoglobin" },
  { label: "Amylase", value: "Amylase" },
  { label: "Lipase", value: "Lipase" },
  { label: "Celiac Disease Panel", value: "Celiac Disease Panel" },
  { label: "Rheumatoid Factor (RF)", value: "Rheumatoid Factor" },
  { label: "Anti-CCP Antibodies", value: "Anti-CCP Antibodies" },
  { label: "Antinuclear Antibody (ANA)", value: "ANA" },
  { label: "Creatinine", value: "Creatinine" },
  { label: "Blood Urea Nitrogen (BUN)", value: "BUN" },
  { label: "Uric Acid", value: "Uric Acid" },
  { label: "Lactic Acid", value: "Lactic Acid" },
  { label: "Ammonia", value: "Ammonia" },
  { label: "Cortisol", value: "Cortisol" },
  { label: "ACTH", value: "ACTH" },
  { label: "Parathyroid Hormone (PTH)", value: "PTH" },
  { label: "Growth Hormone (GH)", value: "GH" },
  { label: "Prolactin", value: "Prolactin" },
  { label: "Estradiol", value: "Estradiol" },
  { label: "Progesterone", value: "Progesterone" },
  { label: "Testosterone", value: "Testosterone" },
  { label: "Follicle Stimulating Hormone (FSH)", value: "FSH" },
  { label: "Luteinizing Hormone (LH)", value: "LH" },
  { label: "Prostate-Specific Antigen (PSA)", value: "PSA" },
  { label: "Electrocardiogram (ECG) Lab Analysis", value: "ECG Lab" },
  { label: "Troponin T", value: "Troponin T" },
  { label: "Creatinine Clearance", value: "Creatinine Clearance" },
  { label: "Urine Sodium", value: "Urine Sodium" },
  { label: "Urine Potassium", value: "Urine Potassium" },
  { label: "Urine Creatinine", value: "Urine Creatinine" },
  { label: "Urine Osmolality", value: "Urine Osmolality" },
  { label: "ABG (Arterial Blood Gas)", value: "ABG" },
  { label: "Blood Gas Analysis", value: "Blood Gas Analysis" },
  { label: "Thyroid Antibodies", value: "Thyroid Antibodies" },
  { label: "Anti-TPO Antibody", value: "Anti-TPO Antibody" },
  {
    label: "Anti-Thyroglobulin Antibody",
    value: "Anti-Thyroglobulin Antibody",
  },
  { label: "Coagulation Profile", value: "Coagulation Profile" },
  { label: "D-Dimer", value: "D-Dimer" },
  { label: "Vitamin K", value: "Vitamin K" },
  { label: "Heavy Metal Panel", value: "Heavy Metal Panel" },
  { label: "Lead", value: "Lead" },
  { label: "Mercury", value: "Mercury" },
  { label: "Cadmium", value: "Cadmium" },
  { label: "Cholesterol Total", value: "Cholesterol Total" },
  { label: "HDL Cholesterol", value: "HDL Cholesterol" },
  { label: "LDL Cholesterol", value: "LDL Cholesterol" },
  { label: "Triglycerides", value: "Triglycerides" },
  { label: "Homocysteine", value: "Homocysteine" },
  { label: "Creatine Phosphokinase (CPK)", value: "CPK" },
  { label: "Celiac Serology", value: "Celiac Serology" },
  { label: "H. Pylori Antibodies", value: "H. Pylori Antibodies" },
  { label: "Fecal Fat Test", value: "Fecal Fat Test" },
  { label: "Stool Culture", value: "Stool Culture" },
  { label: "Stool Parasite Test", value: "Stool Parasite Test" },
  { label: "Sputum Culture", value: "Sputum Culture" },
  { label: "Sputum for AFB", value: "Sputum AFB" },
  { label: "Chlamydia Test", value: "Chlamydia Test" },
  { label: "Gonorrhea Test", value: "Gonorrhea Test" },
  { label: "Syphilis Test (RPR/VDRL)", value: "Syphilis Test" },
  { label: "COVID-19 PCR", value: "COVID-19 PCR" },
  { label: "Influenza A/B PCR", value: "Influenza PCR" },
  { label: "Vitamin A", value: "Vitamin A" },
  { label: "Vitamin E", value: "Vitamin E" },
  { label: "Zinc", value: "Zinc" },
  { label: "Copper", value: "Copper" },
  { label: "Selenium", value: "Selenium" },
  { label: "Magnesium Serum", value: "Magnesium Serum" },
];

export const FrequencyOptions = [
  { label: "Mane", value: "In the morning" },
  { label: "BD", value: "Twice daily (12 hourly)" },
  { label: "TDS", value: "Three times daily (8 hourly)" },
  { label: "QDS", value: "Four times daily (6 hourly)" },
  { label: "Nocte", value: "At night" },
  { label: "Noon", value: "At noon" },
  { label: "Vesper", value: "Evening" },
  { label: "SOS", value: "When necessary" },
  { label: "Stat", value: "Immediately / Once" },
  { label: "EOD", value: "Every other day" },
  { label: "EOW", value: "Every other week" },
  { label: "Weekly", value: "Once a week" },
  { label: "Monthly", value: "Once a month" },
];

export const DoseUnitOptions = [
  { label: "mg", value: "mg" },
  { label: "g", value: "g" },
  { label: "μg", value: "μg" },
  { label: "I.U", value: "I.U" },
  { label: "ml", value: "ml" },
  { label: "drop", value: "drop" },
  { label: "tablet", value: "tablet" },
  { label: "capsule", value: "capsule" },
  { label: "suppo", value: "suppo" },
  { label: "vial", value: "vial" },
  { label: "ampoule", value: "ampoule" },
  { label: "patch", value: "patch" },
  { label: "puff", value: "puff" },
  { label: "lozenge", value: "lozenge" },
  { label: "spray", value: "spray" },
];

export const DurationOptions = [
  { label: "1 day", value: "1 day" },
  { label: "2 days", value: "2 days" },
  { label: "3 days", value: "3 days" },
  { label: "4 days", value: "4 days" },
  { label: "5 days", value: "5 days" },
  { label: "6 days", value: "6 days" },
  { label: "7 days", value: "7 days" },
  { label: "10 days", value: "10 days" },
  { label: "2 weeks", value: "2 weeks" },
  { label: "3 weeks", value: "3 weeks" },
  { label: "4 weeks", value: "4 weeks" },
  { label: "1 month", value: "1 month" },
  { label: "2 months", value: "2 months" },
  { label: "3 months", value: "3 months" },
  { label: "As needed", value: "as needed" },
];

export const RouteOptions = [
  { label: "Oral", value: "Oral" },
  { label: "IM", value: "IM" },
  { label: "IV", value: "IV" },
  { label: "SC", value: "SC" },
  { label: "Rectal", value: "Rectal" },
  { label: "Sublingual", value: "Sublingual" },
  { label: "Buccal", value: "Buccal" },
  { label: "Topical", value: "Topical" },
  { label: "Transdermal", value: "Transdermal" },
  { label: "Inhalation", value: "Inhalation" },
  { label: "Nasal", value: "Nasal" },
  { label: "Ophthalmic (Eye)", value: "Ophthalmic" },
  { label: "Otic (Ear)", value: "Otic" },
  { label: "Intrathecal", value: "Intrathecal" },
  { label: "Epidural", value: "Epidural" },
  { label: "Vaginal", value: "Vaginal" },
  { label: "Intraperitoneal (IP)", value: "IP" },
  { label: "Intracardiac", value: "Intracardiac" },
];
