export const specializationOptions = [
  { label: "Allergy & Immunology", value: "Allergy & Immunology" },
  { label: "Anesthesiology", value: "Anesthesiology" },
  { label: "Cardiology", value: "Cardiology" },
  { label: "Cardiothoracic Surgery", value: "Cardiothoracic Surgery" },
  { label: "Colorectal Surgery", value: "Colorectal Surgery" },
  { label: "Critical Care Medicine", value: "Critical Care Medicine" },
  { label: "Dentistry", value: "Dentistry" },
  { label: "Dermatology", value: "Dermatology" },
  { label: "Emergency Medicine", value: "Emergency Medicine" },
  { label: "Endocrinology", value: "Endocrinology" },
  { label: "ENT (Otolaryngology)", value: "ENT (Otolaryngology)" },
  { label: "OPD M.O", value: "OPD M.O" },
  { label: "Gastroenterology", value: "Gastroenterology" },
  { label: "General Practice", value: "General Practice" },
  { label: "General Physician", value: "General Physician" },
  { label: "General Surgery", value: "General Surgery" },
  { label: "Geriatrics", value: "Geriatrics" },
  { label: "Gynecology", value: "Gynecology" },
  { label: "Gynecologic Oncology", value: "Gynecologic Oncology" },
  { label: "Hematology", value: "Hematology" },
  { label: "Hepatology", value: "Hepatology" },
  { label: "Infectious Disease", value: "Infectious Disease" },
  { label: "Internal Medicine", value: "Internal Medicine" },
  {
    label: "Internal Medicine Physician",
    value: "Internal Medicine Physician",
  }, 
  { label: "Interventional Radiology", value: "Interventional Radiology" },
  { label: "Medical Genetics", value: "Medical Genetics" },
  { label: "Neonatology", value: "Neonatology" },
  { label: "Nephrology", value: "Nephrology" },
  { label: "Neurology", value: "Neurology" },
  { label: "Neurosurgery", value: "Neurosurgery" },
  { label: "Nuclear Medicine", value: "Nuclear Medicine" },
  { label: "Obstetrics & Gynecology", value: "Obstetrics & Gynecology" },
  { label: "Occupational Medicine", value: "Occupational Medicine" },
  { label: "Oncology", value: "Oncology" },
  { label: "Ophthalmology", value: "Ophthalmology" },
  {
    label: "Oral & Maxillofacial Surgery",
    value: "Oral & Maxillofacial Surgery",
  },
  { label: "Orthopedics", value: "Orthopedics" },
  { label: "Pain Management", value: "Pain Management" },
  { label: "Palliative Care", value: "Palliative Care" },
  { label: "Pathology", value: "Pathology" },
  { label: "Pediatrics", value: "Pediatrics" },
  { label: "Pediatric Cardiology", value: "Pediatric Cardiology" },
  { label: "Pediatric Endocrinology", value: "Pediatric Endocrinology" },
  { label: "Pediatric Gastroenterology", value: "Pediatric Gastroenterology" },
  {
    label: "Pediatric Hematology & Oncology",
    value: "Pediatric Hematology & Oncology",
  },
  { label: "Pediatric Nephrology", value: "Pediatric Nephrology" },
  { label: "Pediatric Neurology", value: "Pediatric Neurology" },
  { label: "Pediatric Surgery", value: "Pediatric Surgery" },
  {
    label: "Physical Medicine & Rehabilitation",
    value: "Physical Medicine & Rehabilitation",
  },
  { label: "Plastic Surgery", value: "Plastic Surgery" },
  { label: "Preventive Medicine", value: "Preventive Medicine" },
  { label: "Psychiatry", value: "Psychiatry" },
  { label: "Pulmonology", value: "Pulmonology" },
  { label: "Radiology", value: "Radiology" },
  { label: "Rheumatology", value: "Rheumatology" },
  { label: "Sleep Medicine", value: "Sleep Medicine" },
  { label: "Sports Medicine", value: "Sports Medicine" },
  { label: "Surgical Oncology", value: "Surgical Oncology" },
  { label: "Thoracic Surgery", value: "Thoracic Surgery" },
  { label: "Transplant Surgery", value: "Transplant Surgery" },
  { label: "Trauma Surgery", value: "Trauma Surgery" },
  { label: "Urology", value: "Urology" },
  { label: "Vascular Surgery", value: "Vascular Surgery" },
];
